name: Run End-to-End Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.1'  

    - name: Install dependencies
      run: npm install

    - name: Run server
      run: npx http-server ./src

    - name: Run TestCafe tests
      run: npx testcafe chrome:headless tests/form-test.js
