name: Linting

on:
    push:
        branches:
            - seance4

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12.3'

            - name: Install Flake8
              run: pip install flake8
            
            - name: Run Flake8 LINT
              run: flake8 src/
